project:
  type: book
  output-dir: docs

book:
  title: "用 Python 介绍数据科学"
  subtitle: "从研究、商业和行业中的真实示例"
  author: "The GRAPH Courses"
  cover-image: cover.jpg
  favicon: logo.png
  repo-url: https://github.com/the-graph-courses/idap_book
  repo-branch: main
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Book created by <a href="https://thegraphcourses.org/">The GRAPH Courses</a>
  chapters:
    - index.qmd

    
    ## Use the below for HTML render. (Parts don't seem to work in HTML render)
    - part: "基础知识"
      chapters:
        - p_foundations_google_colab_cn.qmd
        - p_foundations_coding_basics_cn.qmd
        - p_foundations_functions_methods_cn.qmd
        - p_foundations_data_structures_cn.qmd
        - p_foundations_for_loops_cn.qmd
        - p_foundations_writing_functions_cn.qmd
    - part: "数据可视化"
      chapters:
        - p_data_on_display_data_viz_types_cn.qmd
        - p_data_on_display_univariate_cn.qmd
        - p_data_on_display_multivariate_cn.qmd
    - part: "本地 Python 工具"
      chapters:
        - p_tools_installing_python_cn.qmd
        - p_tools_using_vscode_cn.qmd
        - p_tools_venv_cn.qmd
        - p_tools_quarto_cn.qmd
    - part: "数据操作"
      chapters:
        - p_untangled_subset_columns_cn.qmd
        - p_untangled_query_rows_cn.qmd
        - p_untangled_transform_variables_cn.qmd
        - p_untangled_conditional_transforms_cn.qmd
        - p_untangled_groupby_agg_cn.qmd
        - p_untangled_other_grouped_operations_cn.qmd
        - p_untangled_joining_1_cn.qmd
        - p_untangled_joining_2_cn.qmd
        - p_untangled_pivoting_cn.qmd
    - part: "使用 Python 中的 LLM"
      chapters:
        - p_ai_LLM_functions_cn.qmd

resources:
  - CNAME

format:
  # PrettyPDF-pdf:
  #   keep-tex: true
  #   toc: true
  html:
    theme: 
      - cosmo
      # - custom.scss
    css: style.css

editor: source


